# @package _global_

defaults:
  - default.yaml
  - _self_

max_epochs: 50
log_dir: output/dvgt2/train/demo
max_img_per_gpu: 32   # Lowering this value can reduce VRAM consumption.

checkpoint:
  load_pretrained_weights_path_dvgt: null

data_conf:
  train:
    dataset_config:
      - parquet_path: data_annotation/meta/moge_v2_large_correct_focal/moge_pred_filter_parquet/openscene_train_sample_2.parquet
        original_fps: 2
        dataset_len: 1000
        frame_num_max: 38
    sampler_config:
      view_num_range: [2, 8]    # Range of camera views in the dataset
      aspect_ratio_range: [1.6, 3.3]  # Aspect ratio distribution of input images
  val:
    dataset_config:
      - parquet_path: data_annotation/meta/moge_v2_large_correct_focal/moge_pred_filter_parquet/openscene_test_sample_1.parquet
        original_fps: 2
        fixed_aspect_ratio: 1.77