# @package _global_

defaults:
  - /train/dvgt2/default.yaml
  - _self_

log_dir: output/dvgt2/eval/closed_loop/navsim_test_gt
checkpoint_path: null
gt_scale_factor: 1.0

data_conf:
  val:
    common_dataset_config:
      clip_split_type: navtest
    dataset_config:
      - parquet_path: data_annotation/meta/moge_v2_large_correct_focal/moge_pred_filter_parquet/openscene_navtest.parquet
        original_fps: 2
        fixed_aspect_ratio: 1.77

model_wrapper_conf:
  _target_: dvgt.evaluation.models.navsim_test_gt.NavsimTestGTWrapper