# @package _global_

defaults:
  - /_base_/default_log.yaml
  - /_base_/default_dataset.yaml
  - /_base_/default_runtime.yaml
  - _self_

seed_value: 42
log_dir: output/streamvggt/eval/geometry/official_ckpt
checkpoint_path: ckpt/streamvggt/checkpoints.pth
enable_cam: True
enable_trajectory_save: False
gt_scale_factor: 1.0

data_conf:
  val:
    common_dataset_config:
      enable_cam: ${enable_cam}
      patch_size: 14
      image_width: 518
    dataset_config:
      - parquet_path: data_annotation/meta/moge_v2_large_correct_focal/moge_pred_filter_parquet/kitti_val.parquet
        original_fps: 10
        fixed_aspect_ratio: 3.3
      - parquet_path: data_annotation/meta/moge_v2_large_correct_focal/moge_pred_filter_parquet/openscene_test.parquet
        original_fps: 2
        fixed_aspect_ratio: 1.77
      - parquet_path: data_annotation/meta/moge_v2_large_correct_focal/moge_pred_filter_parquet/nuscene_val.parquet
        original_fps: 2
        fixed_aspect_ratio: 1.77
      - parquet_path: data_annotation/meta/moge_v2_large_correct_focal/moge_pred_filter_parquet/waymo_val.parquet
        original_fps: 10
        fixed_aspect_ratio: 1.77
      - parquet_path: data_annotation/meta/moge_v2_large_correct_focal/moge_pred_filter_parquet/ddad_val.parquet
        original_fps: 10
        fixed_aspect_ratio: 1.6

model_wrapper_conf:
  _target_: dvgt.evaluation.models.streamvggt.StreamVGGTWrapper
  eval_config: null